### ISSUE TITLE
NPE is thrown during bootstrap when 'system' agent is initialised

### ISSUE THREAD

**Issue by kovax** [cristal-ise/jooqdb#32]
```
JooqItemPropertyHandler.findItems() - properties:[Property(mName=Name, mValue=system, mMutable=true)]
JooqItemPropertyHandler.findItems() - SQL:
select "Name"."UUID"
from "ITEM_PROPERTY" as "Name"
where (
  "Name"."NAME" = 'Name'
  and "Name"."VALUE" = 'system'
)
Exception in thread "main" java.lang.NullPointerException
	at org.cristalise.storage.jooqdb.lookup.JooqItemHandler.getItemPath(JooqItemHandler.java:191)
	at org.cristalise.storage.jooqdb.lookup.JooqItemHandler.fetch(JooqItemHandler.java:152)
	at org.cristalise.storage.jooqdb.lookup.JooqLookupManager.getAgentPath(JooqLookupManager.java:232)
	at org.cristalise.kernel.process.Bootstrap.checkAgent(Bootstrap.java:462)
	at org.cristalise.kernel.process.Bootstrap.checkAdminAgents(Bootstrap.java:504)
	at org.cristalise.kernel.process.Bootstrap.run(Bootstrap.java:91)
	at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:115)
	at org.cristalise.kernel.process.StandardServer.standardInitialisation(StandardServer.java:128)
	at org.cristalise.kernel.process.StandardServer.main(StandardServer.java:139)
```

**Comment by kovax** [comment]
This happens when the bootstrap finds system agent in the database, and the IS_PASSWORD_TEMPORARY is null, so the Boolen variable cannot be autoboxed to a boolean type.
